version: 2.1
orbs:
  docker: circleci/docker@2.2.0
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          image: $DOCKERHUB_USERNAME/bookstore-website
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASS
